### ISSUE TITLE
Error "can't rename byte as 'sub_*' because the name has a reserved prefix."

### ISSUE THREAD

**Issue by SNMetamorph** [Ayuto/discover_win#2]
IDA Version: 7.3
After running `read_discover_database.py` I got spam in console:
10052F60: can't rename byte as 'sub_10052F60' because the name has a reserved prefix.
10009730: can't rename byte as 'sub_10009730' because the name has a reserved prefix.
10036450: can't rename byte as 'sub_10036450' because the name has a reserved prefix.
1000DC90: can't rename byte as 'sub_1000DC90' because the name has a reserved prefix.
1006B590: can't rename byte as 'sub_1006B590' because the name has a reserved prefix.
1001BCA0: can't rename byte as 'sub_1001BCA0' because the name has a reserved prefix.
10004F70: can't rename byte as 'sub_10004F70' because the name has a reserved prefix.
10011CB0: can't rename byte as 'sub_10011CB0' because the name has a reserved prefix.
1003CEE0: can't rename byte as 'sub_1003CEE0' because the name has a reserved prefix.
10073AA0: can't rename byte as 'sub_10073AA0' because the name has a reserved prefix.
10029D00: can't rename byte as 'sub_10029D00' because the name has a reserved prefix.
100111C0: can't rename byte as 'sub_100111C0' because the name has a reserved prefix.
100298D0: can't rename byte as 'sub_100298D0' because the name has a reserved prefix.
1005D080: can't rename byte as 'sub_1005D080' because the name has a reserved prefix.
10056740: can't rename byte as 'sub_10056740' because the name has a reserved prefix.
10013710: can't rename byte as 'sub_10013710' because the name has a reserved prefix.
100764F0: can't rename byte as 'sub_100764F0' because the name has a reserved prefix.
1003ADE0: can't rename byte as 'sub_1003ADE0' because the name has a reserved prefix.
1006BC00: can't rename byte as 'sub_1006BC00' because the name has a reserved prefix.
10051D80: can't rename byte as 'sub_10051D80' because the name has a reserved prefix.
1003D710: can't rename byte as 'sub_1003D710' because the name has a reserved prefix.
1000DE10: can't rename byte as 'sub_1000DE10' because the name has a reserved prefix.
10077DF0: can't rename byte as 'sub_10077DF0' because the name has a reserved prefix.
1004DE30: can't rename byte as 'sub_1004DE30' because the name has a reserved prefix.
1006B7C0: can't rename byte as 'sub_1006B7C0' because the name has a reserved prefix.

**Comment by Ayuto** [comment]
Just updated the script with a possible fix. Please re-run the updated ``read_discover_database.py`` script to see if it's working.

**Comment by SNMetamorph** [comment]
Yes, it's work
